### ISSUE TITLE
getting OSError 22 While Writing Audio.

### ISSUE THREAD

**Issue by SohamTilekar** [python-ffmpegio/python-ffmpegio#25]
Getting the OSError while writing AudioFile using the Context Manager with ffmpegio.open.

Code Work With ffmpegio.audio.write(...)

Below is the Error Trace Back.
Traceback in Raw format: -
```
Traceback (most recent call last):
  File "d:\soham_code\vidiopy\.py", line 11, in <module>
    audio.write_audiofile(r'D:\soham_code\vidiopy\dump\crunching.wav')
  File "d:\soham_code\vidiopy\vidiopy\audio\AudioClip_native.py", line 243, in write_audiofile
    with ffmpegio.open(url_fg=path,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\soham_code\vidiopy\venv\Lib\site-packages\ffmpegio\__init__.py", line 329, in open
    stream.close()
  File "D:\soham_code\vidiopy\venv\Lib\site-packages\ffmpegio\streams\SimpleStreams.py", line 405, in close
    self._proc.stdin.close()  # flushes the buffer first before closing
    ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

```
Traceback in Rich Format: -
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\soham_code\vidiopy\venv\Lib\site-packages\ffmpegio\__init__.py:326 in open                    │
│                                                                                                  │
│   323 │   # TODO wrap in try-catch if AV stream fails to try a multi-stream version              │
│   324 │   stream = StreamClass(*args, **kwds)                                                    │
│   325 │   try:                                                                                   │
│ ❱ 326 │   │   yield stream                                                                       │
│   327 │   finally:                                                                               │
│   328 │   │   # terminate FFmpeg                                                                 │
│   329 │   │   stream.close()                                                                     │
│                                                                                                  │
│ d:\soham_code\vidiopy\vidiopy\audio\AudioClip_native.py:250 in write_audiofile                   │
│                                                                                                  │
│   247 │   │   │   │   │   │   │      **kwargs) as writer:                                        │
│   248 │   │   │   │   for frame in self._audio_data:                                             │
│   249 │   │   │   │   │                                                                          │
│ ❱ 250 │   │   │   │   │   writer.write(frame)                                                    │
│   251 │   │   else:                                                                              │
│   252 │   │   │   if os.path.isfile(path):                                                       │
│   253 │   │   │   │   raise ValueError(                                                          │
│                                                                                                  │
│ D:\soham_code\vidiopy\venv\Lib\site-packages\ffmpegio\streams\SimpleStreams.py:460 in write      │
│                                                                                                  │
│    457 │   │   │   self._proc.stdin.write(self._viewer(obj=data))                                │
│    458 │   │   except BrokenPipeError as e:                                                      │
│    459 │   │   │   # TODO check log for error in FFmpeg                                          │
│ ❱  460 │   │   │   raise e                                                                       │
│    461 │                                                                                         │
│    462 │   def flush(self):                                                                      │
│    463 │   │   self._proc.stdin.flush()                                                          │
│                                                                                                  │
│ D:\soham_code\vidiopy\venv\Lib\site-packages\ffmpegio\streams\SimpleStreams.py:457 in write      │
│                                                                                                  │
│    454 │   │   logger.debug("[writer main] writing...")                                          │
│    455 │   │                                                                                     │
│    456 │   │   try:                                                                              │
│ ❱  457 │   │   │   self._proc.stdin.write(self._viewer(obj=data))                                │
│    458 │   │   except BrokenPipeError as e:                                                      │
│    459 │   │   │   # TODO check log for error in FFmpeg                                          │
│    460 │   │   │   raise e                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ d:\soham_code\vidiopy\.py:11 in <module>                                                         │
│                                                                                                  │
│    8 ffmpegio.set_path(r'D:\soham_code\vidiopy\vidiopy\binary')                                  │
│    9                                                                                             │
│   10 audio = AudioFileCLip(r'D:\soham_code\vidiopy\media\crunching.mp3')                         │
│ ❱ 11 audio.write_audiofile(r'D:\soham_code\vidiopy\dump\crunching.wav')                          │
│   12                                                                                             │
│                                                                                                  │
│ d:\soham_code\vidiopy\vidiopy\audio\AudioClip_native.py:243 in write_audiofile                   │
│                                                                                                  │
│   240 │   │   if overwrite:                                                                      │
│   241 │   │   │   if os.path.isfile(path):                                                       │
│   242 │   │   │   │   os.remove(path)                                                            │
│ ❱ 243 │   │   │   with ffmpegio.open(url_fg=path,                                                │
│   244 │   │   │   │   │   │   │      mode='wa',                                                  │
│   245 │   │   │   │   │   │   │      rate_in=in_fps,                                             │
│   246 │   │   │   │   │   │   │      rate=fps,                                                   │
│                                                                                                  │
│ C:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Lib\contextlib.py:158 in __exit__        │
│                                                                                                  │
│   155 │   │   │   │   # tell if we get the same exception back                                   │
│   156 │   │   │   │   value = typ()                                                              │
│   157 │   │   │   try:                                                                           │
│ ❱ 158 │   │   │   │   self.gen.throw(value)                                                      │
│   159 │   │   │   except StopIteration as exc:                                                   │
│   160 │   │   │   │   # Suppress StopIteration *unless* it's the same exception that             │
│   161 │   │   │   │   # was passed to throw().  This prevents a StopIteration                    │
│                                                                                                  │
│ D:\soham_code\vidiopy\venv\Lib\site-packages\ffmpegio\__init__.py:329 in open                    │
│                                                                                                  │
│   326 │   │   yield stream                                                                       │
│   327 │   finally:                                                                               │
│   328 │   │   # terminate FFmpeg                                                                 │
│ ❱ 329 │   │   stream.close()                                                                     │
│   330                                                                                            │
│                                                                                                  │
│ D:\soham_code\vidiopy\venv\Lib\site-packages\ffmpegio\streams\SimpleStreams.py:405 in close      │
│                                                                                                  │
│    402 │   │   """close the output stream"""                                                     │
│    403 │   │   if self._proc is None:                                                            │
│    404 │   │   │   return                                                                        │
│ ❱  405 │   │   self._proc.stdin.close()  # flushes the buffer first before closing               │
│    406 │   │   self._proc.wait()                                                                 │
│    407 │   │   self._proc.stderr.close()                                                         │
│    408 │   │   self._logger.join()                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 22] Invalid argument
```

Below is the Imp Code:-
file: - .py
from vidiopy.audio.AudioClip_native import AudioFileCLip
import ffmpegio
from rich import print, traceback
traceback.install()

ffmpegio.set_path(r'D:\soham_code\vidiopy\vidiopy\binary')

audio = AudioFileCLip(r'D:\soham_code\vidiopy\media\crunching.mp3')
audio.write_audiofile(r'D:\soham_code\vidiopy\dump\crunching.wav')

File: - AudioClip.py::write_audiofile

```
    def write_audiofile(self, path: str, fps: int | None = None, overwrite=True, **kwargs):
        if fps is None:
            if self.fps is None:
                raise ValueError('Frames per second (fps) is not set')
            fps = self.fps
        if self._audio_data is None:
            raise ValueError('Audio data is not set')
        if self.duration is None:
            raise ValueError('Original duration is not set')
        if self.channels is None:
            raise ValueError('Channels is not set')

        # ffmpegio.audio.write(path, fps, self._audio_data, ** kwargs)

        # Calculating the in_fps of the audio data using the audio length and the duration
        in_fps = len(self._audio_data) // self.duration

        if overwrite:
            if os.path.isfile(path):
                os.remove(path)
            with ffmpegio.open(url_fg=path, 
                               mode='wa', 
                               rate_in=in_fps, 
                               rate=fps, 
                               **kwargs) as writer:
                for frame in self._audio_data:

                    writer.write(frame)
        else:
            if os.path.isfile(path):
                raise ValueError(
                    'File already exists. Please use a different filename or delete the existing file or put `overwrite=True`.')
            with ffmpegio.open(path, 'w', in_fps, rate=fps, **kwargs) as writer:
                for frame in self._audio_data:
                    writer.write(frame)
        return self
```

Exch Frame Look Like: -
`np.array([0. 0.])`

If You Need Whole Source Code Which Create this Error I Can Give it To You.

**Comment by SohamTilekar** [comment]
> OS: - Windows 10
> ffmpegio version: - 0.9.0
> python Version: - 3.12.1

**Comment by tikuma-lsuhsc** [comment]
> Exch Frame Look Like: -
> `np.array([0. 0.])`

I need a bit more information on your audio data (self._audio_data). How many frames do you have and the dtype and shape of each frame. Also, intended audio channel configuration.

**Comment by SohamTilekar** [comment]
- temp_audio_data: # NumPy Array Which Is Going To Pass
 ```
  [[-6.6625496e-08  0.0000000e+00]
  [ 1.9706306e-03 -4.9242806e-03]
  [ 3.8392330e-03 -7.2298162e-03]
  ...
  [-8.7653788e-08  0.0000000e+00]
  [-8.1950517e-08  0.0000000e+00]
  [-7.6442845e-08  0.0000000e+00]]
 ```
- shape: `(423977, 2)`
- dtype: `float32`
- ndim: `2`
- size: `847954`
- itemsize: `4`
- nbytes: `3391816`
- strides: `(8, 4)`
- flags:
 - C_CONTIGUOUS : `True`
 - F_CONTIGUOUS : `False`
 - OWNDATA : `True`
 - WRITEABLE : `True`
 - ALIGNED : `True`
 - WRITEBACKIFCOPY : `False`
- base: `None`
- ctypes: `<numpy.core._internal._ctypes object at 0x00000273F70C3F20>`
- data: `<memory at 0x00000273F70969B0>
`> Every things Work Fine with `ffmpegio.audio.write(...)`

**Comment by tikuma-lsuhsc** [comment]
Thanks I'll look into it. 

Meanwhile, why are you using the stream write in the code above? Will self._audio_data changes real time (like buffered)? Otherwise, I'd stick to `audio.write()`.

**Comment by SohamTilekar** [comment]
> Meanwhile, why are you using the stream write in the code above?
Answer: -
- There are More Features in the stream write.
  - Like `rate_in` & `rate` separately. but the `audio.write()` do not have it.
- It Make My Code Easy to Read.

---

> Will self._audio_data changes real time (like buffered)?
Ans: -
- It Do not Update in the Real Time.(I am Plaining to add it for Porformance in future).

**Comment by tikuma-lsuhsc** [comment]
> Like rate_in & rate separately. but the audio.write() do not have it.

This you need to familiarize yourself with [FFmpeg options](https://ffmpeg.org/ffmpeg.html). This package is intended to be a convenience wrapper so most functions support all FFmpeg options (or rather they just pass your input to FFmpeg).

So, if you want `audio.write()` to resample, you need to specify `ar` keyword argument so it calls FFmpeg with [the `-ar` option](https://ffmpeg.org/ffmpeg.html#Audio-Options). In other words,

```python
ff.audio.write(path, in_fps, ar=fps. **kwargs)
```

produces the identical output as your `ff.open` call above.

> It Do not Update in the Real Time

Then by all means just use `ff.audio.write` to make your life easier. Although I do appreciate you finding the issues on the features that I rarely use myself :)

> In Which Time Are you online

I'm in the US. Regardless though, I'm not expecting instant responses. Response rate in days is typical in online open source communities in general.

**Comment by tikuma-lsuhsc** [comment]
I was able to reproduce the issue. 

Ironically, it stems from our discussion above on `rate` and `rate_in`. These input arguments are meant to be used together to open FFmpeg in the filter mode (i.e., passing numpy array in to get numpy array out). When you provide both `rate` and `rate_in` **AND** specify `mode` to be not `af` or `vf` it gets confused. 

I will provide a safeguard in the upcoming releases. Meanwhile, the workaround for audio writer is to change the keyword name from `rate` to `ar`:

```python
with ffmpegio.open(url_fg=path, 
                   mode='wa', 
                   rate_in=in_fps, 
                   ar=fps, 
                   **kwargs) as writer:
    for frame in self._audio_data:

        writer.write(frame)
```

**Comment by SohamTilekar** [comment]
I See, 
- But You Do not Bump the version to 9.1v. 
  - You Should Do it Because You Fix the Bug in the Vital Part of the ffmpegio.
- You Should Release this Version.
- You Should Release this Version on the pypi.
- You Should yank the 9.0v in the pypi.
