### ISSUE TITLE
AviStreams AviMediaReader TimeoutError during read

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [python-ffmpegio/python-ffmpegio#46]
This is a bug reported by @cansik on #17 

> Now I face another issue, I would like to read the frames frame by frame. But it seems that ffmpeg is decoding it in the background without me being able to process them quick enough:
> 
> ```python
> import time
> 
> import ffmpegio as ff
> 
> input_path = "test.mkv"
> streams = ["v:0", "v:1", "v:2"]
> 
> i = 0
> with ff.open(str(input_path), "rvv", map=streams, blocksize=1) as fin:
>     while True:
>         F = fin.read()
>         print(f"{i} = {list(F.keys())}")
>         time.sleep(0.1)
> 
>         i += 1
> ```
> 
> When I sleep 0.01 seconds to simulate processing time, the output written is the following (the clip has more than 38 frames). it seems that the iterator is becoming invalid as soon as ffmpeg has finished decoding the frames.
> 
> ```
> 35 = ['v:0', 'v:1', 'v:2']
> 36 = ['v:0', 'v:1', 'v:2']
> 37 = ['v:0', 'v:1', 'v:2']
> 38 = ['v:0', 'v:1', 'v:2']
> Traceback (most recent call last):
>   File "test.py", line 14, in <module>
>     F = fin.read()
>         ^^^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/ffmpegio/streams/AviStreams.py", line 220, in read
>     return self._reader.read(n, ref_stream, timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/ffmpegio/threading.py", line 608, in read
>     raise TimeoutError("timed out waiting for the stream headers")
> TimeoutError: timed out waiting for the stream headers
> ```
> 
> Is this a bug or a feature, and can this be prevented? I already thought the blocksize of 1 would prevent that behaviour. The received frames from the iterator are not skipping, so I think it is more a bug or something I don't understand yet.

**Comment by tikuma-lsuhsc** [comment]
Fixed.
