### ISSUE TITLE
Option hwaccel (use HW accelerated decoding) cannot be applied to output url - -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [python-ffmpegio/python-ffmpegio#8]
In running this code:

```
import ffmpegio
local_src = "vid.mp4"
kwargs = {
  'hwaccel': "cuvid",
  'hwaccel_output_format': "cuda",
  'c:v': "h264_cuvid"
}
fs, F = ffmpegio.video.read(local_src, **kwargs, show_log=True)
```

I get the error:
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/james/PycharmProjects/AlphaPose/Spectronix/RGB_Outputs/SP_vid/SP_vid.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:02.87, start: 0.000000, bitrate: 2058 kb/s
  Stream #0:0[0x1](und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 2055 kb/s, 15 fps, 15 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Option hwaccel (use HW accelerated decoding) cannot be applied to output url - -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file -.
Error opening output files: Invalid argument
Traceback (most recent call last):
  File "/snap/pycharm-community/302/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/302/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/james/PycharmProjects/AlphaPose/Spectronix/Early_Experiments/vid_gpu_decode.py", line 19, in <module>
    fs, F = ffmpegio.video.read(local_src, **kwargs, show_log=True)
  File "/home/james/anaconda3/envs/alphapose/lib/python3.7/site-packages/ffmpegio/video.py", line 192, in read
    r_in=r_in,
  File "/home/james/anaconda3/envs/alphapose/lib/python3.7/site-packages/ffmpegio/video.py", line 52, in _run_read
    raise FFmpegError(out.stderr)
ffmpegio.utils.error.FFmpegError: FFmpeg terminated abnormally with the error:

  FFmpeg failed for unknown reason (no log available). It seems like for whatever reason the arguments are not being parsed in the right order.

Any thoughts on how to fix this?
Thanks.

**Comment by tikuma-lsuhsc** [comment]
Sorry that the streaming part of the package is still minimally documented.

A few tips:

* Remember that the input options requires `'_in'` added to the FFmpeg option name. If you don't, it assumes that the given option is that for the output (which what the error message is implying). So, `-hwaccel` option is an input option 
* When you browse [FFmpeg documentation](https://ffmpeg.org/ffmpeg.html) keep your eyes on whether an option of your interest says `"-option_name ... (input...)" then you need to add `_in` to the option name.
* To show the FFmpeg log, call `open(..., show_log=True)`
* To create a log file, call `open(..., report=None)`
* Your hwaccel options look outdated (could be wrong) See [this wiki article](https://trac.ffmpeg.org/wiki/HWAccelIntro#NVDECCUVID).

Now, you can try

``` python
kwargs = {
  'hwaccel_in': "cuda",
}
```

or

``` python
kwargs = {
  ''c:v_in': "h264_cuvid",
}
```

See either works.

**Comment by JamesMcCullochDickens** [comment]
Hi, thanks for the help!
So, a new error message from both the above suggestions is (along with the below)
kwargs = {
  'c:v_in': "h264_cuvid",
  'hwaccel_output_format_in': "cuda"
}
fs, F = ffmpegio.video.read(local_src, **kwargs, show_log=True)

Requested output format 'rawvideo' is not a suitable output format. This might be more of an ffmpeg issue than your repo, but if you have any tips that would be much appreciated.

**Comment by tikuma-lsuhsc** [comment]
Actually, that part is very much with the tool. I've never tested it with hardware acceleration. Anyway, try

``` python
fs, F = ffmpegio.video.read(local_src, sample_fmt='rgb24', **kwargs)
```


P.S., when you post code, add a line with "``` python" before and after your code lines. That'll make it easier to read

**Comment by JamesMcCullochDickens** [comment]
So writing 
```
kwargs = {
  'c:v_in': "h264_cuvid"
}
fs, F = ffmpegio.video.read(local_src, sample_fmt='rgb24', **kwargs)
```
```
now gives an error:
 File "/home/james/PycharmProjects/AlphaPose/Spectronix/Early_Experiments/vid_gpu_decode.py", line 17, in <module>
    fs, F = ffmpegio.video.read(local_src, sample_fmt='rgb24', **kwargs)
  File "/home/james/anaconda3/envs/alphapose/lib/python3.7/site-packages/ffmpegio/video.py", line 192, in read
    r_in=r_in,
  File "/home/james/anaconda3/envs/alphapose/lib/python3.7/site-packages/ffmpegio/video.py", line 52, in _run_read
    raise FFmpegError(out.stderr)
ffmpegio.utils.error.FFmpegError: FFmpeg terminated abnormally with the error:

  FFmpeg failed for unknown reason (no log available).

```

**Comment by tikuma-lsuhsc** [comment]
This I need FFmpeg log, run

``` python
fs, F = ffmpegio.video.read(local_src, sample_fmt='rgb24', **kwargs, show_log=True)
```

and copy me the FFmpeg log. thx

BTW, if you need to overwrite existing file, add `overwrite=True` argument to it as well.

**Comment by tikuma-lsuhsc** [comment]
Wait, I mixed up the video & audio format options, it's `pix_fmt`. Try

```python
fs, F = ffmpegio.video.read(local_src, pix_fmt='rgb24', **kwargs, show_log=True)
```

**Comment by JamesMcCullochDickens** [comment]
> Wait, I mixed up the video & audio format options, it's `pix_fmt`. Try
> 
> ```python
> fs, F = ffmpegio.video.read(local_src, pix_fmt='rgb24', **kwargs, show_log=True)
> ```

Gives the error [NULL @ 0x55622dafdc00] Requested output format 'rawvideo' is not a suitable output format.

**Comment by tikuma-lsuhsc** [comment]
Could you copy the FFmpeg log? This must be something CUDA related. You may need to manually move video frames from GPU to CPU memory space

**Comment by JamesMcCullochDickens** [comment]
Sorry I didn't realize the log was above the error, here it is:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/james/Desktop/file_example_MP4_480_1_5MG.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2015-08-07T09:13:02.000000Z
  Duration: 00:00:30.53, start: 0.000000, bitrate: 411 kb/s
  Stream #0:0[0x1](und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 480x270 [SAR 1:1 DAR 16:9], 301 kb/s, 30 fps, 30 tbr, 30 tbn (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 112 kb/s (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Audio Handler
      vendor_id       : [0][0][0][0]
[NULL @ 0x55622dafdc00] Requested output format 'rawvideo' is not a suitable output format
pipe:: Invalid argument
```

**Comment by tikuma-lsuhsc** [comment]
hmm, a couple things to try.

1. see if it works if you drop `**kwargs` (software decode)
2. run with `loglevel='debug'` to see more log (with hardware decode)

**Comment by JamesMcCullochDickens** [comment]
Running `fs, F = ffmpegio.video.read(local_src, pix_fmt='rgb24', show_log=True, loglevel="debug")`, yields
```
Splitting the commandline.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Reading option '-nostdin' ... matched as option 'stdin' (enable or disable interaction on standard input) with argument 0.
Reading option '-hide_banner' ... matched as option 'hide_banner' (do not show program banner) with argument '1'.
Reading option '-i' ... matched as input url with argument '/home/james/Desktop/file_example_MP4_480_1_5MG.mp4'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'rgb24'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Applying option nostdin (enable or disable interaction on standard input) with argument 0.
Applying option hide_banner (do not show program banner) with argument 1.
Successfully parsed a group of options.
Parsing a group of options: input url /home/james/Desktop/file_example_MP4_480_1_5MG.mp4.
Successfully parsed a group of options.
Opening an input file: /home/james/Desktop/file_example_MP4_480_1_5MG.mp4.
[NULL @ 0x557b825da700] Opening '/home/james/Desktop/file_example_MP4_480_1_5MG.mp4' for reading
[file @ 0x557b825dae40] Setting default whitelist 'file,crypto,data'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] ISO: File Type Major Brand: mp42
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] Unknown dref type 0x206c7275 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] Processing st: 0, edit list 0 - media time: 0, duration: 901
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] Unknown dref type 0x206c7275 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] Processing st: 1, edit list 0 - media time: 0, duration: 1465280
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] Before avformat_find_stream_info() pos: 11872 bytes read:32768 seeks:0 nb_streams:2
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] parser not found for codec h264, packets or times may be invalid.
[h264 @ 0x557b825dbd40] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x557b825dbd40] nal_unit_type: 8(PPS), nal_ref_idc: 3
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] parser not found for codec h264, packets or times may be invalid.
[h264 @ 0x557b825dbd40] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x557b825dbd40] nal_unit_type: 5(IDR), nal_ref_idc: 3
[h264 @ 0x557b825dbd40] Format yuv420p chosen by get_format().
[h264 @ 0x557b825dbd40] Reinit context to 480x272, pix_fmt: yuv420p
[h264 @ 0x557b825dbd40] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
    Last message repeated 5 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] All info found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557b825da700] After avformat_find_stream_info() pos: 45135 bytes read:65536 seeks:0 frames:32
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/james/Desktop/file_example_MP4_480_1_5MG.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2015-08-07T09:13:02.000000Z
  Duration: 00:00:30.53, start: 0.000000, bitrate: 411 kb/s
  Stream #0:0[0x1](und), 31, 1/30: Video: h264 (Constrained Baseline), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 480x270 (480x272) [SAR 1:1 DAR 16:9], 0/1, 301 kb/s, 30 fps, 30 tbr, 30 tbn (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und), 1, 1/48000: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 112 kb/s (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Audio Handler
      vendor_id       : [0][0][0][0]
Successfully opened the file.
Parsing a group of options: output url -.
Applying option pix_fmt (set pixel format) with argument rgb24.
Applying option f (force format) with argument rawvideo.
Successfully parsed a group of options.
Opening an output file: -.
[NULL @ 0x557b82601480] Requested output format 'rawvideo' is not a suitable output format
pipe:: Invalid argument
[AVIOContext @ 0x557b825e3200] Statistics: 65536 bytes read, 0 seeks
```

**Comment by JamesMcCullochDickens** [comment]
When running with kwargs I get:
```

Splitting the commandline.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Reading option '-nostdin' ... matched as option 'stdin' (enable or disable interaction on standard input) with argument 0.
Reading option '-hide_banner' ... matched as option 'hide_banner' (do not show program banner) with argument '1'.
Reading option '-c:v' ... matched as option 'c' (codec name) with argument 'h264_cuvid'.
Reading option '-i' ... matched as input url with argument '/home/james/Desktop/file_example_MP4_480_1_5MG.mp4'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'rgb24'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Applying option nostdin (enable or disable interaction on standard input) with argument 0.
Applying option hide_banner (do not show program banner) with argument 1.
Successfully parsed a group of options.
Parsing a group of options: input url /home/james/Desktop/file_example_MP4_480_1_5MG.mp4.
Applying option c:v (codec name) with argument h264_cuvid.
Successfully parsed a group of options.
Opening an input file: /home/james/Desktop/file_example_MP4_480_1_5MG.mp4.
[NULL @ 0x557835041700] Opening '/home/james/Desktop/file_example_MP4_480_1_5MG.mp4' for reading
[file @ 0x557835041e40] Setting default whitelist 'file,crypto,data'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] ISO: File Type Major Brand: mp42
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] Unknown dref type 0x206c7275 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] Processing st: 0, edit list 0 - media time: 0, duration: 901
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] Unknown dref type 0x206c7275 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] Processing st: 1, edit list 0 - media time: 0, duration: 1465280
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] Before avformat_find_stream_info() pos: 11872 bytes read:32768 seeks:0 nb_streams:2
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] parser not found for codec h264, packets or times may be invalid.
[h264 @ 0x557835042d40] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x557835042d40] nal_unit_type: 8(PPS), nal_ref_idc: 3
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] parser not found for codec h264, packets or times may be invalid.
[h264 @ 0x557835042d40] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x557835042d40] nal_unit_type: 5(IDR), nal_ref_idc: 3
[h264 @ 0x557835042d40] Format yuv420p chosen by get_format().
[h264 @ 0x557835042d40] Reinit context to 480x272, pix_fmt: yuv420p
[h264 @ 0x557835042d40] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
    Last message repeated 5 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] All info found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x557835041700] After avformat_find_stream_info() pos: 45135 bytes read:65536 seeks:0 frames:32
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/james/Desktop/file_example_MP4_480_1_5MG.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2015-08-07T09:13:02.000000Z
  Duration: 00:00:30.53, start: 0.000000, bitrate: 411 kb/s
  Stream #0:0[0x1](und), 31, 1/30: Video: h264 (Constrained Baseline), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 480x270 (480x272) [SAR 1:1 DAR 16:9], 0/1, 301 kb/s, 30 fps, 30 tbr, 30 tbn (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und), 1, 1/48000: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 112 kb/s (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Audio Handler
      vendor_id       : [0][0][0][0]
Successfully opened the file.
Parsing a group of options: output url -.
Applying option pix_fmt (set pixel format) with argument rgb24.
Applying option f (force format) with argument rawvideo.
Successfully parsed a group of options.
Opening an output file: -.
[NULL @ 0x557835067b00] Requested output format 'rawvideo' is not a suitable output format
pipe:: Invalid argument
[AVIOContext @ 0x55783504a200] Statistics: 65536 bytes read, 0 seeks
```

**Comment by tikuma-lsuhsc** [comment]
It's the output config not working correctly. 

Compared to your line:

```
Opening an output file: -.
[NULL @ 0x557835067b00] Requested output format 'rawvideo' is not a suitable output format
```

I get

```
Opening an output file: -.
[pipe @ 0000020cccce0400] Setting default whitelist 'crypto,data'
```

Are you on Linux? Also, what's the FFmpeg version? One more, can you find where `ffmpegio` package is installed? (I use venv so it's `.venv/Lib/site-packages/ffmpegio`)

**Comment by tikuma-lsuhsc** [comment]
Let's bypass the reader functionality for now. Could you try this:

```python
ffmpegio.ffmpeg(f'-loglevel debug -nostdin -hide_banner -i {local_src} -pix_fmt rgb24 -f rawvideo -vframes 1 pipe:1')
```

(the last argument `pipe:1` was `-`)

**Comment by JamesMcCullochDickens** [comment]
I am on Ubuntu 22.04, my ffmpeg version is:
ffmpeg -version
```
ffmpeg version N-108641-g25e1986e68 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --disable-static --enable-shared --nvccflags='-gencode arch=compute_86,code=sm_86 -O2' --disable-doc --disable-bsfs --disable-decoders --disable-encoders --disable-filters --disable-demuxers --disable-devices --disable-muxers --disable-parsers --disable-postproc --disable-protocols --enable-decoder=aac --enable-decoder=h264 --enable-decoder=h264_cuvid --enable-decoder=rawvideo --enable-indev=lavfi --enable-encoder=libx264 --enable-encoder=h264_nvenc --enable-demuxer=mov --enable-muxer=mp4 --enable-filter=scale --enable-filter=testsrc2 --enable-protocol=file --enable-protocol=https --enable-gnutls --enable-shared --enable-gpl --enable-nonfree --enable-cuda-nvcc --enable-libx264 --enable-nvenc --enable-cuvid --enable-nvdec
libavutil      57. 39.101 / 57. 39.101
libavcodec     59. 50.100 / 59. 50.100
libavformat    59. 34.101 / 59. 34.101
libavdevice    59.  8.101 / 59.  8.101
libavfilter     8. 49.101 /  8. 49.101
libswscale      6.  8.112 /  6.  8.112
libswresample   4.  9.100 /  4.  9.100
```
My ffmpegio is installed in a conda environment /home/james/anaconda3/envs/alphapose/lib/python3.7/site-packages.

**Comment by JamesMcCullochDickens** [comment]
> Let's bypass the reader functionality for now. Could you try this:
> 
> ```python
> ffmpegio.ffmpeg(f'-loglevel debug -nostdin -hide_banner -i {local_src} -pix_fmt rgb24 -f rawvideo -vframes 1 pipe:1')
> ```
> 
> (the last argument `pipe:1` was `-`)

I ran this and it seems to have worked, returncode of 1.

**Comment by tikuma-lsuhsc** [comment]
Unfortunately, `returncode=1` means it's not working. Does it end with the same error? ("Requested output format 'rawvideo' is not a suitable output format")

**Comment by JamesMcCullochDickens** [comment]
Oh, my mistake. The error is the same yes. Perhaps I should do more research and come back in a few days, I'm a total noob when it comes to this topic unfortunately.

**Comment by tikuma-lsuhsc** [comment]
No no, it's fine. I'm excited to see someone trying to use my library and I'm sorry it's causing an issue. This package has been tested in Ubuntu but using plain python and not conda. But, the FFmpeg error isn't really related to the python. I haven't tested nightly builds though. You can try downloading v5.1 release (which is what I'm running currently).
